#!/usr/bin/env python3

import roslib
import rospy

from template_python_node.main import TemplatePythonNode

NODE_NAME = 'template_python_node'
roslib.load_manifest(NODE_NAME)

if __name__ == '__main__':
    rospy.init_node(NODE_NAME)
    try:
        node = TemplatePythonNode()
    except rospy.ROSInterruptException:
        pass
